/**
 * Passages français dans les textes anglais des pages /en/trajet/<slug>.
 *
 * Relevé du 2026-10-03 : les descriptions anglaises des fichiers de données
 * reprennent les « points forts » (highlights) saisis en français, et parfois
 * l'itinéraire (« Via A8 sortie 44 », « ring road sud », « Navette aéroport »).
 * Sur les 867 pages anglaises, 687 servaient ainsi une meta description
 * mêlant français et anglais (« Roues à aubes and Brocante en route »),
 * mesuré dans le HTML en ligne ; noms propres de lieux non comptés.
 *
 * Plutôt que de dupliquer les highlights par langue dans plus de 200 fichiers,
 * on traduit ici, une fois, chaque libellé français rencontré. Les noms propres
 * de lieux restent tels quels (Mérignac, Saint-Émilion, Château de Chambord,
 * Place Stanislas…) ; les noms communs et les génériques sont traduits
 * (« Navette » → « shuttle », « Lac d'Annecy » → « Lake Annecy »).
 *
 * Les traductions sont en casse de phrase : un nom commun reste en minuscule
 * au milieu d'une liste, et la majuscule de début de phrase est remise après.
 */

/**
 * Libellés traduits partout où ils apparaissent (le texte français est assez
 * spécifique pour ne pas se confondre avec un mot anglais).
 */
const PHRASES_EN: Record<string, string> = {
  // Routes et itinéraires
  "21 virages": "21 hairpin bends",
  "225 km pistes": "225 km of ski runs",
  "24 Heures": "24 Hours of Le Mans",
  "A1 Autoroute du Nord": "A1 motorway",
  "A1 direction Lille": "A1 towards Lille",
  "A1/Périphérique/A6": "A1, ring road and A6",
  "A10 italienne": "Italian A10",
  "A10 L'Aquitaine": "A10 motorway",
  "A104 Francilienne": "A104 outer ring road",
  "A11 direction Le Mans": "A11 towards Le Mans",
  "A11 L'Océane": "A11 motorway",
  "A13 / A12 direction Trappes": "A13 / A12 towards Trappes",
  "A13 Autoroute de Normandie": "A13 motorway",
  "A13 direction Caen": "A13 towards Caen",
  "A13 direction Rouen": "A13 towards Rouen",
  "A13 puis A132": "A13 then A132",
  "A16 direction Boulogne": "A16 towards Boulogne",
  "A20 L'Occitane": "A20 motorway",
  "A4 Autoroute de l'Est": "A4 motorway",
  "A4 direction Metz": "A4 towards Metz",
  "A4 L'Est": "A4 motorway",
  "A40 Autoroute Blanche": "A40 motorway",
  "A5 direction Troyes": "A5 towards Troyes",
  "A6 Autoroute du Soleil": "A6 motorway",
  "A6/A7 Autoroute du Soleil": "A6/A7 motorway",
  "A64 la Pyrénéenne": "A64 motorway",
  "A65 Autoroute de Gascogne": "A65 motorway",
  "A65 puis A64": "A65 then A64",
  "A7 Autoroute du Soleil": "A7 motorway",
  "A71 Autoroute d'Auvergne": "A71 motorway",
  "A75 Méridienne": "A75 motorway",
  "Autoroute A1": "A1 motorway",
  "Autoroute A10/A7": "A10/A7 motorways",
  "Autoroute A3": "A3 motorway",
  "Autoroute A40/A41": "A40/A41 motorways",
  "Autoroute A43": "A43 motorway",
  "Autoroute A6": "A6 motorway",
  "Autoroute Blanche A40": "A40 motorway",
  "Autoroute de Normandie": "Normandy motorway",
  "Autoroute de Provence": "Provence motorway",
  "Autoroute directe": "direct motorway",
  "Autoroute du Nord": "A1 motorway",
  "Autoroute du Soleil A7": "A7 motorway",
  "Autoroute du Soleil": "A6/A7 motorway",
  "Autoroute Esterel": "Esterel motorway",
  "Autoroute des Fleurs": "the Italian A10 motorway",
  "Boulevard périphérique": "Paris ring road",
  "Périphérique Est": "eastern ring road",
  "Périphérique Ouest": "western ring road",
  "Périphérique sud": "southern ring road",
  "Périphérique Sud": "southern ring road",
  "Périphérique": "ring road",
  "ring road sud": "southern ring road",
  "ring road Ouest": "western ring road",
  "Rocade bordelaise": "Bordeaux ring road",
  "Rocade": "ring road",
  "Route directe": "direct road",
  "Route D117": "D117 road",
  "Route N124": "N124 road",
  "Route N193": "N193 road",
  "Route N196": "N196 road",
  "Route N197": "N197 road",
  "RN205 Route Blanche": "RN205 road",
  "N20 historique": "historic N20",
  "N141/RN141": "N141",
  "M20 Angleterre": "M20 to England",
  "Voie express": "expressway",
  "Pénétrante Grasse": "Grasse access road",
  "Francilienne": "outer ring road",
  "Traversée Bretagne-Paris": "Brittany to Paris drive",
  "Traversée Italie": "drive into Italy",
  "Longue distance": "long distance",
  "Porte-à-porte": "door-to-door",
  "Trajet porte-à-porte": "door-to-door ride",
  "Desserte gare/aéroport": "station and airport transfers",
  "Transfert gare/aéroport": "station and airport transfers",
  "Navette directe CDG — Disneyland sans détour": "direct CDG to Disneyland shuttle, no detour",
  "Navette directe CDG, Disneyland sans détour": "direct CDG to Disneyland shuttle, no detour",
  "Liaison directe": "direct link",
  "Trajet longue distance": "long-distance ride",
  "Navette aéroport": "airport shuttle",
  "Navette croisière": "cruise shuttle",
  "Transfert croisière": "cruise transfer",
  "Navette ferry": "ferry shuttle",
  "Navette Orly": "Orly shuttle",
  "Navette rapide": "fast shuttle",
  "Navette vol": "flight shuttle",
  "Navette": "shuttle",
  "Retour business": "business return trip",
  "Retour degustation": "return after a tasting",
  "Retour festival": "return after the festival",
  "Retour vacances": "holiday return trip",
  "Retour weekend": "weekend return trip",
  "Dimanche soir": "Sunday evening",
  "Vol international": "international flights",
  "TGV alternative": "alternative to the TGV",
  "Gare TGV aéroport": "airport TGV station",
  "Gare TGV Massy": "Massy TGV station",
  "Gare TGV": "TGV station",
  "Gare Lille-Europe": "Lille-Europe station",
  "Gare Saint-Charles": "Saint-Charles station",
  "Gare Saint-Jean": "Saint-Jean station",
  "Gare de Colombes": "Colombes station",
  "Aéroport Beauvais-Tillé": "Beauvais-Tillé Airport",
  "Aéroport Blagnac": "Blagnac Airport",
  "Aéroport BOD": "Bordeaux Airport (BOD)",
  "Aéroport CDG": "CDG Airport",
  "Aéroport d'Orly": "Orly Airport",
  "Aéroport Dinard-Pleurtuit-Saint-Malo": "Dinard-Pleurtuit-Saint-Malo Airport",
  "Aéroport El Prat": "El Prat Airport",
  "Aéroport GVA": "Geneva Airport (GVA)",
  "Aéroport Marignane": "Marignane Airport",
  "Aéroport MPL": "Montpellier Airport (MPL)",
  "Aéroport Nice Côte d'Azur": "Nice Côte d'Azur Airport",
  "Aéroport Nice": "Nice Airport",
  "Aéroport NTE": "Nantes Airport (NTE)",
  "Aéroport Orly": "Orly Airport",
  "Aéroport Toulouse-Blagnac": "Toulouse-Blagnac Airport",
  "Aéroport": "the airport",
  "Héliport de Paris": "Paris Heliport",
  "Base aérienne 921": "Air Base 921",
  "Bac du Verdon": "Le Verdon ferry",
  "Sièges enfants disponibles sur demande": "child seats on request",
  "Frontière allemande": "German border",
  "Frontière belge": "Belgian border",
  "Frontière espagnole": "Spanish border",
  "Frontière italienne": "Italian border",
  "Frontière suisse": "Swiss border",
  "Frontière": "the border",
  "Frontaliers": "cross-border commuters",
  "Transfrontalier": "cross-border",
  "Transmanche": "Channel crossing",
  "Tunnel sous la Manche": "Channel Tunnel",
  "Tunnel du Fréjus": "Fréjus Tunnel",
  "Tunnel du Mont-Blanc": "Mont Blanc Tunnel",
  "Trois frontières": "three borders",
  "Pays des Trois Frontières": "Three Borders area",
  "Franco-allemand": "Franco-German",
  "Deux capitales lorraines": "two Lorraine capitals",
  "Aire de Beaune-Tailly": "Beaune-Tailly rest area",

  // Noms propres protégés (contiennent un mot traduit ailleurs)
  "Boulevard des Pyrénées": "Boulevard des Pyrénées",
  "Nantes Atlantique": "Nantes Atlantique",
  "Côtes du Rhône": "Côtes du Rhône",
  "Côte de Beaune": "Côte de Beaune",
  "Côte d'Opale": "Côte d'Opale",
  "Marne-la-Vallée": "Marne-la-Vallée",

  // Pays, régions, fleuves (exonymes anglais usuels)
  "Allemagne": "Germany",
  "Alpes Mancelles": "Alpes Mancelles",
  "Alpes": "Alps",
  "Alsace du Nord": "northern Alsace",
  "Anvers": "Antwerp",
  "Atlantique": "Atlantic coast",
  "Avant-Pays Savoyard": "Savoyard foothills",
  "Bade-Wurtemberg": "Baden-Württemberg",
  "Bade": "Baden",
  "Belgique": "Belgium",
  "Bocage breton": "Breton bocage",
  "Bocage normand": "Normandy bocage",
  "Bocage": "bocage countryside",
  "Bourgogne": "Burgundy",
  "Bretagne": "Brittany",
  "Bruxelles": "Brussels",
  "Catalogne Nord": "Northern Catalonia",
  "Catalogne": "Catalonia",
  "Champagne sud": "southern Champagne",
  "Champagne-Sud": "southern Champagne",
  "Corse": "Corsica",
  "Courtrai": "Kortrijk",
  "Espagne": "Spain",
  "Finistère Sud": "southern Finistère",
  "Flandre": "Flanders",
  "Forêt-Noire": "Black Forest",
  "Gascogne": "Gascony",
  "Gênes": "Genoa",
  "Genevois savoyard": "Savoyard Genevois",
  "Grand-Duché": "Grand Duchy",
  "Isère Nord": "northern Isère",
  "Italie": "Italy",
  "Languedoc méditerranéen": "Mediterranean Languedoc",
  "Ligurie": "Liguria",
  "Méditerranée": "Mediterranean",
  "Moselle-Est": "eastern Moselle",
  "Nord Médoc": "northern Médoc",
  "Normandie-Maine": "Normandy-Maine",
  "Normandie": "Normandy",
  "Océan": "the ocean",
  "Pays basque": "Basque Country",
  "Pays Basque": "Basque Country",
  "Pays cathare": "Cathar Country",
  "Pays Cathare": "Cathar Country",
  "Pays de Brie": "Brie country",
  "Pays de Cocagne": "Pays de Cocagne",
  "Pays-Bas": "the Netherlands",
  "Périgord blanc": "White Périgord",
  "Périgord noir": "Black Périgord",
  "Périgord Noir": "Black Périgord",
  "Picardie maritime": "coastal Picardy",
  "Picardie": "Picardy",
  "Piémont pyrénéen": "Pyrenean foothills",
  "Piémont": "Piedmont",
  "Pré-Pyrénées": "Pyrenean foothills",
  "Pyrénées ariégeoises": "Ariège Pyrenees",
  "Pyrénées centrales": "central Pyrenees",
  "Pyrénées": "Pyrenees",
  "Rhin": "Rhine",
  "Rhône": "Rhône",
  "Riviera italienne": "Italian Riviera",
  "Sarre": "Saarland",
  "Savoie": "Savoy",
  "Suisse Normande": "Suisse Normande",
  "Suisse": "Switzerland",
  "Wallonie": "Wallonia",
  "Catalogne Sud": "southern Catalonia",
  "Arrière-pays": "hinterland",
  "Haute Tinée": "upper Tinée valley",
  "Haut-Var": "upper Var",
  "Massif central": "Massif Central",
  "Côte basque": "Basque coast",
  "Côte Basque": "Basque coast",
  "Côte varoise": "Var coast",
  "Corniche basque": "Basque coast road",
  "Corniche Basque": "Basque coast road",
  "Basse Corniche": "lower corniche road",
  "Moyenne Corniche": "middle corniche road",
  "Principauté": "the Principality",
  "Capitale bretonne": "Breton capital",
  "Capitale catalane": "Catalan capital",
  "Capitale de la gastronomie": "capital of gastronomy",
  "Capitale du parfum": "perfume capital",
  "Capitale": "the capital",
  "Métropole": "metropolitan area",
  "Nantes métropole": "Nantes metropolitan area",
  "Narbonnaise": "Narbonne area",
  "Narbonne romaine": "Roman Narbonne",
  "Vienne romaine": "Roman Vienne",
  "Ville rose": "the Pink City",
  "Ville Rose": "the Pink City",
  "Ville impériale": "imperial town",
  "Ville haute fortifiée": "fortified upper town",
  "Haute Ville de Granville": "Granville upper town",
  "Venise du Gâtinais": "Venice of the Gâtinais",
  "Venise provençale": "Venice of Provence",
  "Petite Venise": "Little Venice",
  "Petite France": "Petite France district",
  "Premier duché": "first duchy",
  "Rive sud": "south bank",
  "Proximité Fréjus": "near Fréjus",
  "Préfecture 77": "Seine-et-Marne prefecture",
  "Préfecture 92": "Hauts-de-Seine prefecture",
  "Préfecture Ardèche": "Ardèche prefecture",
  "Préfecture du Val-de-Marne": "Val-de-Marne prefecture",
  "Préfecture Marne": "Marne prefecture",
  "Préfecture": "prefecture",
  "Sous-préfecture des Alpes-de-Haute-Provence": "sub-prefecture of Alpes-de-Haute-Provence",
  "Porte de la Provence": "gateway to Provence",
  "Porte des Alpes": "gateway to the Alps",
  "Porte des stations": "gateway to the ski resorts",
  "Porte de Monaco": "gateway to Monaco",

  // Monuments et sites
  // Points forts affichés seulement dans la liste visible de la page
  "Maison Jeanne d'Arc": "Joan of Arc House",
  "Cathédrale Saint-Julien": "Saint-Julien Cathedral",
  "Vignoble de l'Anjou": "Anjou vineyards",
  "Festival BD": "comics festival",
  "Forêt landaise": "Landes forest",
  "Cathédrale de la Sède": "La Sède Cathedral",
  "Château fort": "fortified castle",
  "Station balnéaire chic": "upmarket seaside resort",
  "Casemates du Bock": "Bock Casemates",
  "Galettes": "Breton galettes",
  "Festival Interceltique": "Interceltic Festival",
  "Haute ville": "upper town",
  "Chartres en lumières": "Chartres light show",
  "Plages de Pampelonne": "Pampelonne beaches",
  "Perché": "hilltop setting",
  "Autoroute A104 puis A4 direction Marne-la-Vallée": "A104 then A4 towards Marne-la-Vallée",
  "Autoroute A8": "A8 motorway",
  "Autoroute A7": "A7 motorway",
  "Autoroute A68": "A68 motorway",
  "Autoroute": "motorway",
  "Transfert direct CDG — Disneyland sans détour": "direct CDG to Disneyland transfer, no detour",
  "Transfert direct": "direct transfer",
  "Transfert ferry": "ferry transfer",
  "Transfert vol": "flight transfer",
  "Transfert international": "international transfer",
  "Transfert aéroport": "airport transfer",
  "Transfert rapide": "fast transfer",
  "Transfert gare": "station transfer",
  "Transfert longue distance": "long-distance transfer",
  "Transfert Orly": "Orly transfer",
  "Transfert porte-à-porte": "door-to-door transfer",
  "Transfert": "transfer",
  "Gratuit": "free",
  "Prise en charge à tous les terminaux CDG": "pick-up at every CDG terminal",
  "Service 24h/24 y compris jours fériés": "24/7 service, public holidays included",
  "Vol long-courrier": "long-haul flights",
  "Long-courrier": "long-haul",
  "Bagages": "luggage",
  "Gare Fontainebleau-Avon": "Fontainebleau-Avon station",
  "Commune jumelle": "twin town",
  "Résidents": "residents",
  "Village des peintres": "painters' village",
  "24h/24": "24/7",
  "Suivi vol": "flight tracking",
  "Vieux-Port de Cannes": "Cannes Old Port",
  "Citadelle de Bastia": "Bastia Citadel",
  "Bouches de Bonifacio": "Strait of Bonifacio",
  "Maquis et villages perchés": "maquis and hilltop villages",
  "Vallée du Tavignano": "Tavignano valley",
  "Bêtises": "Bêtises de Cambrai sweets",
  "Cathédrale de Troyes": "Troyes Cathedral",
  "Haute montagne": "high mountains",
  "Châtaigneraie cantalienne": "Cantal chestnut country",
  "Week-end": "weekend",
  "Hareng de Dieppe": "Dieppe herring",
  "Truffe noire": "black truffles",
  "Canal de Bourgogne": "Burgundy Canal",
  "Bords de Marne": "Marne riverbanks",
  "Proche Roissy": "close to Roissy",
  "Canal de l'Ourcq": "Ourcq Canal",
  "Ultra-proche": "very close",
  "Sans autoroute": "no motorway",
  "Zone commerciale": "shopping area",
  "Haute Dordogne": "upper Dordogne",
  "Deux stations thermales": "two spa towns",
  "Aquarium": "aquarium",
  "Baie de Douarnenez": "Bay of Douarnenez",
  "Baie de Morlaix": "Bay of Morlaix",
  "Baie de Saint-Brieuc": "Bay of Saint-Brieuc",
  "Baie de Somme": "Somme Bay",
  "Baie des Anges": "Bay of Angels",
  "Baie du Mont-Saint-Michel": "Mont-Saint-Michel Bay",
  "Baie Mont-Saint-Michel": "Mont-Saint-Michel Bay",
  "Baie du Mont": "Mont-Saint-Michel Bay",
  "Bassin d'Arcachon": "Arcachon Bay",
  "Bord de mer": "seafront",
  "Chorégies": "Chorégies opera festival",
  "Cathares": "Cathars",
  "Drôme provençale": "Provençal Drôme",
  "La Pyrénéenne": "A64 motorway",
  "Printemps de Bourges": "Printemps de Bourges festival",
  "Vosges du Nord": "Northern Vosges",
  "Abbaye de Sénanque": "Sénanque Abbey",
  "Abbaye du Mont-Saint-Michel": "Mont-Saint-Michel Abbey",
  "Abbaye du Thoronet": "Le Thoronet Abbey",
  "Abbaye Saint-Michel-de-Cuxa": "Saint-Michel-de-Cuxa Abbey",
  "Abbaye Saint-Michel": "Saint-Michel Abbey",
  "Abbaye": "abbey",
  "Agneau mystique": "Ghent Altarpiece",
  "Aiguille creuse": "Hollow Needle",
  "Aiguilles de Bavella": "Bavella needles",
  "Amphithéâtre romain": "Roman amphitheatre",
  "Aquarium La Rochelle": "La Rochelle Aquarium",
  "Arènes de Nîmes": "Nîmes Arena",
  "Arènes romaines": "Roman arena",
  "Arènes": "Roman arena",
  "Auberge Ravoux": "Ravoux Inn",
  "Avenue de Champagne": "Avenue de Champagne",
  "Banc d'Arguin": "Arguin sandbank",
  "Base sous-marine": "submarine base",
  "Basilique Saint-Denis": "Saint-Denis Basilica",
  "Basilique Saint-Denys": "Saint-Denys Basilica",
  "Basilique Sainte-Thérèse": "Sainte-Thérèse Basilica",
  "Basilique": "basilica",
  "Bataille de Verdun": "Battle of Verdun",
  "Bataille de Poitiers": "Battle of Poitiers",
  "Bec de l'Aigle": "Eagle's Beak cliff",
  "Beffroi Béthune": "Béthune belfry",
  "Beffroi de Lille": "Lille belfry",
  "Beffroi UNESCO Douai": "Douai UNESCO belfry",
  "Beffroi UNESCO": "UNESCO belfry",
  "Beffroi": "belfry",
  "Bergerie nationale": "national sheep farm",
  "Bibliothèque humaniste": "Humanist Library",
  "Bois de Boulogne": "Bois de Boulogne",
  "Bords de Seine": "Seine riverbanks",
  "Boucles de la Seine": "Seine meanders",
  "Butte de Montmorency": "Montmorency hill",
  "Cabanes tchanquées": "stilt huts",
  "Calanques de Théoule": "Théoule coves",
  "Calanques": "calanques",
  "Canal de Garonne": "Garonne Canal",
  "Canal de la Marne au Rhin": "Marne-Rhine Canal",
  "Canal de la Robine": "Robine Canal",
  "Canal de Nantes à Brest": "Nantes-Brest Canal",
  "Canal du Midi UNESCO": "Canal du Midi (UNESCO)",
  "Canaux": "canals",
  "Carrières de Lumières": "Carrières de Lumières",
  "Casino de Baden-Baden": "Baden-Baden Casino",
  "Casino Monte-Carlo": "Monte-Carlo Casino",
  "Casino Barrière": "Barrière Casino",
  "Catacombes": "Catacombs",
  "Cathédrale Amiens UNESCO": "Amiens Cathedral (UNESCO)",
  "Cathédrale d'Amiens": "Amiens Cathedral",
  "Cathédrale d'Évry": "Évry Cathedral",
  "Cathédrale d'Orléans": "Orléans Cathedral",
  "Cathédrale de Beauvais": "Beauvais Cathedral",
  "Cathédrale de Béziers": "Béziers Cathedral",
  "Cathédrale de Chartres": "Chartres Cathedral",
  "Cathédrale de Reims": "Reims Cathedral",
  "Cathédrale de Rodez": "Rodez Cathedral",
  "Cathédrale de Rouen": "Rouen Cathedral",
  "Cathédrale de Sens": "Sens Cathedral",
  "Cathédrale de Strasbourg": "Strasbourg Cathedral",
  "Cathédrale des sacres": "coronation cathedral",
  "Cathédrale du Puy": "Le Puy Cathedral",
  "Cathédrale en brique": "brick cathedral",
  "Cathédrale gothique": "Gothic cathedral",
  "Cathédrale inachevée": "unfinished cathedral",
  "Cathédrale Monet": "Monet's cathedral",
  "Cathédrale Notre-Dame de Chartres": "Chartres Cathedral",
  "Cathédrale Saint-Alain": "Saint-Alain Cathedral",
  "Cathédrale Saint-Bavon": "St Bavo's Cathedral",
  "Cathédrale Saint-Corentin": "Saint-Corentin Cathedral",
  "Cathédrale Saint-Etienne": "Saint-Étienne Cathedral",
  "Cathédrale Saint-Étienne Metz": "Metz Cathedral",
  "Cathédrale Saint-Étienne": "Saint-Étienne Cathedral",
  "Cathédrale Saint-Front": "Saint-Front Cathedral",
  "Cathédrale Saint-Just": "Saint-Just Cathedral",
  "Cathédrale Saint-Lazare": "Saint-Lazare Cathedral",
  "Cathédrale Saint-Maclou": "Saint-Maclou Cathedral",
  "Cathédrale Saint-Nazaire": "Saint-Nazaire Cathedral",
  "Cathédrale Saint-Pierre": "Saint-Pierre Cathedral",
  "Cathédrale Saint-Samson": "Saint-Samson Cathedral",
  "Cathédrale Sainte-Cécile": "Sainte-Cécile Cathedral",
  "Cathédrale Sainte-Croix": "Sainte-Croix Cathedral",
  "Cathédrale Sainte-Marie": "Sainte-Marie Cathedral",
  "Cathédrale UNESCO": "UNESCO cathedral",
  "Cathédrale": "the cathedral",
  "Causse Méjean": "Causse Méjean plateau",
  "Causses du Quercy": "Quercy causses",
  "Causses": "causses plateaus",
  "Grands Causses UNESCO": "Grands Causses (UNESCO)",
  "Centre Pompidou-Metz": "Centre Pompidou-Metz",
  "Chaîne des Puys": "Chaîne des Puys volcanoes",
  "Chantiers navals": "shipyards",
  "Chapelle Cocteau": "Cocteau Chapel",
  "Chapelle royale": "royal chapel",
  "Château des ducs": "Castle of the Dukes",
  "Château des Dames": "Château des Dames",
  "Château fort de Sedan": "Sedan Castle",
  "Château Guillaume le Conquérant": "William the Conqueror's Castle",
  "Château impérial": "imperial palace",
  "Château médiéval": "medieval castle",
  "Château Renaissance": "Renaissance château",
  "Château royal": "royal château",
  "Château Royal": "royal château",
  "Château UNESCO": "UNESCO château",
  "Château de Versailles": "Palace of Versailles",
  "Château de Fontainebleau": "Palace of Fontainebleau",
  "Château Henri IV": "Henri IV's castle",
  "Château": "château",
  "Châteaux de la Loire": "Loire châteaux",
  "Châteaux": "châteaux",
  "Cinéma Lumière": "Lumière cinema",
  "Circuit des 24 Heures": "24 Hours circuit",
  "Circuit Magny-Cours": "Magny-Cours circuit",
  "Citadelle de Calvi": "Calvi Citadel",
  "Citadelle de Corte": "Corte Citadel",
  "Citadelle de Sisteron": "Sisteron Citadel",
  "Citadelle de Vauban": "Vauban citadel",
  "Citadelle génoise": "Genoese citadel",
  "Citadelle Vauban": "Vauban citadel",
  "Citadelle XVIe": "16th-century citadel",
  "Citadelle": "citadel",
  "Cité corsaire": "corsair city",
  "Cité de l'Automobile": "Cité de l'Automobile museum",
  "Cité de l'Espace": "Cité de l'Espace",
  "Cité de la BD": "comics museum",
  "Cité de la Gastronomie": "Cité de la Gastronomie",
  "Cité de la Mer": "Cité de la Mer",
  "Cité de la Tapisserie": "tapestry museum",
  "Cité de la Voile": "sailing museum",
  "Cité des Images": "Cité des Images",
  "Cité des Violettes": "City of Violets",
  "Cité du Train": "railway museum",
  "Cité du Vin": "Cité du Vin",
  "Cité épiscopale": "episcopal city",
  "Cité médiévale de Pérouges": "medieval town of Pérouges",
  "Cité médiévale des peintres impressionnistes": "medieval town of the Impressionist painters",
  "Cité médiévale UNESCO": "UNESCO medieval city",
  "Cité médiévale": "medieval city",
  "Cité royale": "royal city",
  "Cité sacrée": "sacred city",
  "Clairière de l'Armistice": "Armistice Glade",
  "Climats UNESCO": "Burgundy climats (UNESCO)",
  "Clue de Sisteron": "Sisteron gorge",
  "Col Bayard": "Col Bayard pass",
  "Collégiale de Mantes": "Mantes collegiate church",
  "Collégiale Notre-Dame-en-Vaux": "Notre-Dame-en-Vaux collegiate church",
  "Collégiale Saint-Vulfran": "Saint-Vulfran collegiate church",
  "Collégiale": "collegiate church",
  "Colline Saint-Jacques": "Saint-Jacques hill",
  "Confluence du Loing et de la Seine": "confluence of the Loing and the Seine",
  "Confluence Vienne-Clain": "Vienne-Clain confluence",
  "Confluent Dordogne": "Dordogne confluence",
  "Coteaux de Gascogne": "Gascony hillsides",
  "Côtes de Meuse": "Meuse hills",
  "Coulée Verte": "Coulée Verte greenway",
  "Défilé de Lancone": "Lancone gorge",
  "Digue promenade": "seafront promenade",
  "Dolmen de la Pierre de la Fée": "Pierre de la Fée dolmen",
  "Donjon": "keep",
  "Dune du Pilat": "Dune du Pilat",
  "Dune": "sand dune",
  "Écluse ronde": "round lock",
  "Écluses de Fonseranes": "Fonseranes locks",
  "Église d'Auvers": "Auvers church",
  "Église monolithe": "monolithic church",
  "Église Notre-Dame-la-Grande": "Notre-Dame-la-Grande church",
  "Église Notre-Dame": "Notre-Dame church",
  "Église Saint-Jean-Baptiste": "Saint-Jean-Baptiste church",
  "Église Saint-Martin": "Saint-Martin church",
  "Enclos paroissiaux": "parish closes",
  "Escalier monumental": "monumental staircase",
  "Estuaire de la Gironde": "Gironde estuary",
  "Estuaire de la Loire": "Loire estuary",
  "Estuaire de la Seine": "Seine estuary",
  "Estuaire Gironde": "Gironde estuary",
  "Étang de Berre": "Étang de Berre lagoon",
  "Étang de Leucate": "Leucate lagoon",
  "Étang de Thau": "Thau lagoon",
  "Étang de Trivaux": "Trivaux pond",
  "Bassin de Thau": "Thau lagoon",
  "Bassin houiller": "coalfield",
  "Bassin minier UNESCO": "UNESCO mining basin",
  "Bassin minier": "mining basin",
  "Faculté de médecine": "medical school",
  "Falaises d'Étretat": "Étretat cliffs",
  "Falaises de Bonifacio": "Bonifacio cliffs",
  "Falaises": "cliffs",
  "Forêt d'Ancenis": "Ancenis forest",
  "Forêt de Bord": "Bord forest",
  "Forêt de Brocéliande": "Brocéliande forest",
  "Forêt de Compiègne": "Compiègne forest",
  "Forêt de Fontainebleau": "Fontainebleau forest",
  "Forêt de Haguenau": "Haguenau forest",
  "Forêt de Juigné": "Juigné forest",
  "Forêt de Meudon": "Meudon forest",
  "Forêt de Montmorency": "Montmorency forest",
  "Forêt de pins": "pine forest",
  "Forêt de Rambouillet": "Rambouillet forest",
  "Forêt de Vizzavona": "Vizzavona forest",
  "Forêt des Landes": "Landes forest",
  "Forêt domaniale": "state forest",
  "Forêt Landaise": "Landes forest",
  "Forêts": "forests",
  "Forêt": "forest",
  "Fort d'Issy": "Fort d'Issy",
  "Forteresse royale": "royal fortress",
  "Forteresse Vauban": "Vauban fortress",
  "Fortifications Vauban": "Vauban fortifications",
  "Four solaire": "solar furnace",
  "Glacier de Mont-de-Lans": "Mont-de-Lans glacier",
  "Golfe de Fos": "Gulf of Fos",
  "Golfe de Saint-Tropez": "Gulf of Saint-Tropez",
  "Golfe du Morbihan": "Gulf of Morbihan",
  "Golf de Riviera": "Riviera golf course",
  "Gorges de la Vésubie": "Vésubie gorges",
  "Gorges du Cians": "Cians gorges",
  "Gorges du Loup": "Loup gorges",
  "Gorges du Tarn": "Tarn gorges",
  "Gorges du Verdon": "Verdon Gorge",
  "Gouffre de Padirac": "Padirac chasm",
  "Grand Bassin": "Grand Bassin",
  "Grand Canyon d'Europe": "Grand Canyon of Europe",
  "Grand ensemble de Sarcelles": "Sarcelles housing estate",
  "Grand Hôtel de Cabourg": "Cabourg Grand Hôtel",
  "Grand-Place flamande": "Flemish main square",
  "Grand-Place Arras": "Arras Grand-Place",
  "Grand-Place Bruxelles": "Brussels Grand-Place",
  "Grande Arche de La Défense": "Grande Arche at La Défense",
  "Grande Île UNESCO": "Grande Île (UNESCO)",
  "Grande Plage": "main beach",
  "Grandes Eaux et cascades": "fountains and cascades",
  "Grandes Écuries": "Great Stables",
  "Grands crus classés": "classified grands crus",
  "Gravures rupestres": "rock engravings",
  "Grotte de Massabielle": "Massabielle grotto",
  "Grottes de Cougnac": "Cougnac caves",
  "Haras de Tarbes": "Tarbes stud farm",
  "Haras nationaux": "national stud farms",
  "Hôpital Percy": "Percy hospital",
  "Hospices de Beaune": "Hospices de Beaune",
  "Île aux Oiseaux": "Bird Island",
  "Îles d'Or": "Golden Isles",
  "Îles de Lérins": "Lérins Islands",
  "Îles Chausey": "Chausey Islands",
  "Jardin du Luxembourg": "Luxembourg Gardens",
  "Jardin exotique": "exotic garden",
  "Jardin Exotique": "exotic garden",
  "Jardins de la Fontaine": "Jardins de la Fontaine",
  "Jardins de Le Nôtre": "Le Nôtre gardens",
  "Jardins de Menton": "Menton gardens",
  "Jardins de Monet": "Monet's gardens",
  "Jardins de Versailles": "Gardens of Versailles",
  "Jardins de Villandry": "Villandry gardens",
  "Jardins impressionnistes": "Impressionist gardens",
  "Jardins": "gardens",
  "Jet d'eau": "Jet d'Eau fountain",
  "Lac d'Aiguebelette": "Lake Aiguebelette",
  "Lac d'Annecy": "Lake Annecy",
  "Lac d'Hossegor": "Lake Hossegor",
  "Lac Daumesnil": "Lake Daumesnil",
  "Lac de breil": "Breil lake",
  "Lac de Castillon": "Lake Castillon",
  "Lac de Créteil": "Lake Créteil",
  "Lac de Saint-Ferréol": "Lake Saint-Ferréol",
  "Lac de Sainte-Croix": "Lake Sainte-Croix",
  "Lac de Serre-Ponçon": "Lake Serre-Ponçon",
  "Lac de Vassivière": "Lake Vassivière",
  "Lac du Bourget": "Lake Bourget",
  "Lac du Sautet": "Lake Sautet",
  "Lac Léman": "Lake Geneva",
  "Lac Pavin": "Lake Pavin",
  "Lacs": "lakes",
  "Loire à Orléans": "the Loire at Orléans",
  "Loire-Cher confluence": "Loire-Cher confluence",
  "Machines de l'île": "Machines de l'Île",
  "Maison de Claude Monet": "Claude Monet's house",
  "Maison de la Magie": "House of Magic",
  "Maison Louis XIV": "Louis XIV's house",
  "Maison Van Gogh": "Van Gogh house",
  "Maisons à colombages": "half-timbered houses",
  "Maisons à pans de bois": "half-timbered houses",
  "Maisons à pondalez": "pondalez houses",
  "Maisons de Champagne": "Champagne houses",
  "Maisons sur l'Agout": "houses on the Agout",
  "Manufacture d'armes": "arms factory",
  "Maquettes 1/30e de monuments": "1:30 scale monument models",
  "Maquis corse": "Corsican maquis",
  "Marais de Dol": "Dol marshes",
  "Marais poitevin": "Poitevin marshes",
  "Marais Poitevin": "Poitevin marshes",
  "Marais salants": "salt marshes",
  "Marché aux fleurs": "flower market",
  "Marché de Noël": "Christmas market",
  "Marché de Rungis": "Rungis market",
  "Marché de Saint-Denis": "Saint-Denis market",
  "Marché de Vintimille": "Ventimiglia market",
  "Marché nocturne": "night market",
  "Marché provençal": "Provençal market",
  "Marché sur l'eau": "floating market",
  "Marché": "market",
  "Marche limousine": "Limousin borderlands",
  "Marches de Bretagne": "Breton marches",
  "Marine nationale": "French Navy",
  "Massif de l'Estérel": "Estérel massif",
  "Massif de la Chartreuse": "Chartreuse massif",
  "Massif des Bornes": "Bornes massif",
  "Massif des Maures": "Maures massif",
  "Massif du Salève": "Salève massif",
  "Mémorial 14-18": "WWI memorial",
  "Mémorial de Caen": "Caen Memorial",
  "Mémorial de la cote 204": "Hill 204 memorial",
  "Mémorial": "memorial",
  "Menhir du Champ-Dolent": "Champ-Dolent menhir",
  "Merveille de l'Occident": "Wonder of the West",
  "Mine témoin": "mining museum",
  "Monastère de Brou": "Royal Monastery of Brou",
  "Mont Blanc": "Mont Blanc",
  "Montagne Noire": "Montagne Noire",
  "Montagne Sainte-Victoire": "Mont Sainte-Victoire",
  "Monts de Tarare": "Tarare hills",
  "Monts du Forez": "Forez mountains",
  "Monts du Lyonnais": "Lyonnais hills",
  "Musée alsacien": "Alsatian Museum",
  "Musée Condé": "Condé Museum",
  "Musée de l'Annonciade": "Annonciade Museum",
  "Musée de la Chartreuse": "Chartreuse Museum",
  "Musée de la Photo": "photography museum",
  "Musée de Préhistoire": "museum of prehistory",
  "Musée des beaux-arts": "fine arts museum",
  "Musée des Beaux-Arts": "fine arts museum",
  "Musée des Merveilles": "Musée des Merveilles",
  "Musée Fernand Léger": "Fernand Léger Museum",
  "Musée Goya": "Goya Museum",
  "Musée Picasso": "Picasso Museum",
  "Musée Soulages": "Soulages Museum",
  "Musée Toulouse-Lautrec": "Toulouse-Lautrec Museum",
  "Musée Unterlinden": "Unterlinden Museum",
  "Olivier millénaire": "thousand-year-old olive tree",
  "Opéra de Massy": "Massy opera house",
  "Ossuary de Douaumont": "Douaumont Ossuary",
  "Palais des Congrès": "convention centre",
  "Palais des Festivals": "Palais des Festivals",
  "Palais des Papes": "Palace of the Popes",
  "Palais des Rois de Majorque": "Palace of the Kings of Majorca",
  "Palais impérial": "imperial palace",
  "Parc d'attractions": "theme park",
  "Parc de Vilgénis": "Vilgénis park",
  "Parc des Expositions de Villepinte": "Villepinte exhibition centre",
  "Parc des Expositions": "exhibition centre",
  "Parc du Château": "castle park",
  "Parc du Mercantour": "Mercantour National Park",
  "Parc historique de 460 hectares": "460-hectare historic park",
  "Parc Kennedy": "Kennedy park",
  "Parc National": "national park",
  "Parc Zoologique de Paris": "Paris Zoo",
  "Parcours en plein air": "open-air trail",
  "Parcs à huîtres": "oyster beds",
  "Parlement de Bretagne": "Brittany Parliament",
  "Parlement de Flandre": "Flanders Parliament",
  "Parlement européen": "European Parliament",
  "Parlement": "parliament",
  "Passage du Gois": "Passage du Gois causeway",
  "Pastels Quentin de La Tour": "Quentin de La Tour pastels",
  "Phare des Baleines": "Phare des Baleines lighthouse",
  "Phare": "lighthouse",
  "Pic du Midi à proximité": "Pic du Midi nearby",
  "Piste olympique de bobsleigh": "Olympic bobsleigh track",
  "Place Stanislas UNESCO": "Place Stanislas (UNESCO)",
  "Plage de La Baule": "La Baule beach",
  "Plage de Pampelonne": "Pampelonne beach",
  "Plage des Deux Jumeaux": "Deux Jumeaux beach",
  "Plage des Estagnots": "Estagnots beach",
  "Plage du Touquet": "Le Touquet beach",
  "Plage Mala": "Mala beach",
  "Plage Sword Beach": "Sword Beach",
  "Plages de Porto-Vecchio": "Porto-Vecchio beaches",
  "Plages de sable fin": "fine sandy beaches",
  "Plages du Débarquement": "D-Day beaches",
  "Plages lacustres": "lakeside beaches",
  "Plages méditerranéennes": "Mediterranean beaches",
  "Plages océanes": "ocean beaches",
  "Plages vendéennes": "Vendée beaches",
  "Plages": "beaches",
  "Plage": "the beach",
  "Plaine d'Alsace": "Alsace plain",
  "Plaine de l'Est lyonnais": "eastern Lyon plain",
  "Plaine de Limagne": "Limagne plain",
  "Plaine de Pamiers": "Pamiers plain",
  "Planches de Deauville": "Deauville boardwalk",
  "Planches": "the boardwalk",
  "Plateau de Millevaches": "Millevaches plateau",
  "Plateau de Saclay": "Saclay plateau",
  "Plateau du Larzac": "Larzac plateau",
  "Plateau du Léon": "Léon plateau",
  "Plus beau village de France": "one of France's most beautiful villages",
  "Plus beau village": "one of France's most beautiful villages",
  "Plus beaux villages": "most beautiful villages",
  "Plus haute dune d'Europe": "Europe's highest dune",
  "Polders de la Digue": "Digue polders",
  "Pont d'Argenteuil": "Argenteuil bridge",
  "Pont d'Oléron": "Oléron bridge",
  "Pont de Kehl": "Kehl bridge",
  "Pont de l'Europe": "Europe Bridge",
  "Pont de Normandie": "Normandy Bridge",
  "Pont de Ré": "Île de Ré bridge",
  "Pont de Saint-Nazaire": "Saint-Nazaire bridge",
  "Pont de Sèvres": "Pont de Sèvres",
  "Pont suspendu": "suspension bridge",
  "Pont Vieux fortifié": "fortified old bridge",
  "Pont vieux médiéval": "medieval old bridge",
  "Pont Vieux": "old bridge",
  "Pont-canal": "canal bridge",
  "Pont-levis": "drawbridge",
  "Porcelaine de Limoges": "Limoges porcelain",
  "Porcelaine": "porcelain",
  "Port autonome": "commercial port",
  "Port de Cassis": "Cassis harbour",
  "Port de Cherbourg": "Cherbourg harbour",
  "Port de la Rance": "Rance harbour",
  "Port de Pauillac": "Pauillac harbour",
  "Port de pêche": "fishing port",
  "Port de plaisance": "marina",
  "Port de Roscoff": "Roscoff harbour",
  "Port de Saint-Tropez": "Saint-Tropez harbour",
  "Port de Toulon": "Toulon harbour",
  "Port médiéval": "medieval port",
  "Port militaire": "naval port",
  "Port provençal": "Provençal harbour",
  "Port-Musée": "Port-Musée maritime museum",
  "Potager ornemental": "ornamental kitchen garden",
  "Prieuré Saint-Nicolas": "Saint-Nicolas priory",
  "Presqu'île de Giens": "Giens peninsula",
  "Presqu'île mythique": "legendary peninsula",
  "Presqu'île": "the peninsula",
  "Quais de Seine": "Seine embankments",
  "quais de Seine": "the Seine embankments",
  "Quartier Atlantis": "Atlantis district",
  "Quartier Latin": "Latin Quarter",
  "Quartier Saint-Leu": "Saint-Leu quarter",
  "Rade de Brest": "Brest harbour",
  "Rade de Lorient": "Lorient harbour",
  "Rade de Toulon": "Toulon harbour",
  "Rade de Villefranche": "Villefranche bay",
  "Rade": "the harbour",
  "Remparts de Saint-Malo": "Saint-Malo ramparts",
  "Remparts": "ramparts",
  "Retable de Mirailhet": "Mirailhet altarpiece",
  "Roc surplombant le village": "rock overlooking the village",
  "Roche de Solutré": "Rock of Solutré",
  "Rocher Corneille": "Rocher Corneille",
  "Rocher de la Vierge": "Rocher de la Vierge",
  "Rocher de Roquebrune": "Roquebrune rock",
  "Roches rouges de l'Estérel": "red rocks of the Estérel",
  "Roches rouges": "red rocks",
  "Roller coasters Toutatis & OzIris": "Toutatis & OzIris roller coasters",
  "Roues à aubes": "paddle wheels",
  "Route des Calanques": "Calanques road",
  "Route des Champagnes": "Champagne route",
  "Route des Châteaux": "Châteaux route",
  "Route des Crêtes": "Route des Crêtes",
  "Route des Grands Crus": "Grands Crus wine route",
  "Route des Vins": "Wine Route",
  "Ruines romaines": "Roman ruins",
  "Sacre des Rois": "coronation of kings",
  "Safari en voiture": "drive-through safari",
  "Sanctuaire de Lourdes": "Lourdes sanctuary",
  "Sanctuaire marial": "Marian shrine",
  "Sanctuaires de Lourdes": "Lourdes sanctuaries",
  "Sanctuaires": "sanctuaries",
  "Santons d'Aubagne": "Aubagne santons",
  "Saut des Français": "Saut des Français viewpoint",
  "Sentier du littoral": "coastal path",
  "Sèvre niortaise": "Sèvre Niortaise river",
  "Sources de la Marne": "source of the Marne",
  "Spectacle nocturne": "night show",
  "Stade Bollaert": "Bollaert stadium",
  "Stade Yves-du-Manoir": "Yves-du-Manoir stadium",
  "Station balnéaire Belle Époque": "Belle Époque seaside resort",
  "Station balnéaire": "seaside resort",
  "Station chic": "upmarket resort",
  "Station de ski familiale": "family ski resort",
  "Station de ski": "ski resort",
  "Station familiale": "family resort",
  "Station verte": "green resort",
  "Stations de ski": "ski resorts",
  "Tapisserie Apocalypse": "Apocalypse Tapestry",
  "Tapisserie de l'Apocalypse": "Apocalypse Tapestry",
  "Tapisserie UNESCO": "UNESCO tapestry",
  "Tapisseries": "tapestries",
  "Tapisserie": "tapestry",
  "Théâtre antique": "Roman theatre",
  "Thermes Caracalla": "Caracalla baths",
  "Thermes": "thermal baths",
  "Tombe de Van Gogh": "Van Gogh's grave",
  "Tour de Guinette": "Guinette tower",
  "Tour du Bassin": "around the bay",
  "Tour Eiffel": "Eiffel Tower",
  "Train des Merveilles": "Train des Merveilles",
  "Train Jaune": "Yellow Train",
  "Université de Corse": "University of Corsica",
  "Val de Loire": "Loire Valley",
  "Vallée de l'Argens": "Argens valley",
  "Vallée de l'Arve": "Arve valley",
  "Vallée de l'Aven": "Aven valley",
  "Vallée de l'Eure": "Eure valley",
  "Vallée de l'Oise": "Oise valley",
  "Vallée de l'Ubaye": "Ubaye valley",
  "Vallée de la Bévéra": "Bévéra valley",
  "Vallée de la Creuse": "Creuse valley",
  "Vallée de la Dordogne": "Dordogne valley",
  "Vallée de la Juine": "Juine valley",
  "Vallée de la Moselle": "Moselle valley",
  "Vallée de la Rance": "Rance valley",
  "Vallée de la Roya": "Roya valley",
  "vallée de la Roya": "through the Roya valley",
  "vallée du Var puis vallée de la Vaïre": "Var valley then Vaïre valley",
  "vallée du Var": "Var valley",
  "vallée de la Vésubie": "Vésubie valley",
  "vallée de la Vaïre": "Vaïre valley",
  "route de Vence": "Vence road",
  "route d'Auch": "Auch road",
  "pas d'autoroute": "no motorway",
  "autoroute Est": "eastern motorway",
  "autoroute du Val de Durance": "Durance valley motorway",
  "L'Autoroute de Gascogne": "Gascony motorway",
  "Autoroute de Gascogne": "Gascony motorway",
  "Autoroute de la Côte Basque": "Basque Coast motorway",
  "Autoroute des Fleurs (A10 italienne)": "the Italian A10 motorway",
  "voie express": "expressway",
  "gratuite": "toll-free",
  "pont Kehl": "Kehl bridge",
  "périphérique": "ring road",
  "La Provençale": "La Provençale",
  "Route Napoléon": "Route Napoléon",
  "Route Bleue": "Route Bleue",
  "Vallée de la Seine": "Seine valley",
  "Vallée de la Siagne": "Siagne valley",
  "Vallée de la Vésubie": "Vésubie valley",
  "Vallée de la Vézère": "Vézère valley",
  "Vallée des Merveilles": "Vallée des Merveilles",
  "Vallée du Gier": "Gier valley",
  "Vallée du Lot": "Lot valley",
  "Vallée du Rhône": "Rhône valley",
  "Vallée du Var": "Var valley",
  "Verrerie artisanale": "glassblowing workshops",
  "Viaduc de Millau": "Millau Viaduct",
  "Viaduc de Morlaix": "Morlaix viaduct",
  "Viaduc de Veauce": "Veauce viaduct",
  "Vieille ville d'Annecy": "Annecy old town",
  "Vieille ville fortifiée": "fortified old town",
  "Vieille ville La Pigna": "La Pigna old town",
  "Vieille ville médiévale": "medieval old town",
  "Vieille ville provençale": "Provençal old town",
  "Vieille ville": "old town",
  "Vieux Bassin": "Old Harbour",
  "Vieux Chinon": "old Chinon",
  "Vieux Tours": "old Tours",
  "Vieux-Port de Marseille": "Marseille Old Port",
  "Vieux-Port": "Old Port",
  "Village alpin": "Alpine village",
  "Village authentique": "authentic village",
  "Village de Picasso": "Picasso's village",
  "Village historique": "historic village",
  "Village médiéval": "medieval village",
  "Village perché": "hilltop village",
  "Village provençal": "Provençal village",
  "Villages ostréicoles": "oyster villages",
  "Villages perchés": "hilltop villages",
  "Villas Belle Époque": "Belle Époque villas",
  "Ville Close de Concarneau": "Concarneau walled town",
  "Ville Close": "walled town",
  "Ville d'Hiver": "Winter Town",
  "Vitraux médiévaux": "medieval stained glass",
  "Vitraux": "stained glass",
  "Volcans d'Auvergne UNESCO": "Auvergne volcanoes (UNESCO)",
  "Volcans d'Auvergne": "Auvergne volcanoes",
  "Volcans": "volcanoes",
  "Volcan": "volcano",
  "Vue panoramique sur Paris": "panoramic view of Paris",
  "Vue panoramique": "panoramic view",
  "Vue sur la Méditerranée": "Mediterranean views",
  "Vue sur les collines de Grasse": "views over the Grasse hills",
  "Zone industrielle": "industrial area",
  "Zoo à pied": "walk-through zoo",
  "Ligne Maginot": "Maginot Line",
  "Bambouseraie": "bamboo garden",
  "Hortillonnages": "floating gardens",
  "Troglodytes": "troglodyte dwellings",
  "Pyramides": "pyramids",
  "Romains": "Roman heritage",
  "Romaine": "Roman heritage",
  "Halles": "covered market",
  "Écusson": "Écusson old town",
  "Grand Hôtel": "Grand Hôtel",

  // Gastronomie, produits, vin
  "Berlingots": "berlingot sweets",
  "Bêtises de Cambrai": "Bêtises de Cambrai sweets",
  "Chocolat basque": "Basque chocolate",
  "Chocolat": "chocolate",
  "Confiture de groseilles": "redcurrant jam",
  "Foie gras": "foie gras",
  "Fromages": "cheeses",
  "Fruits confits": "candied fruit",
  "Gastronomie étoilée": "Michelin-starred dining",
  "Gastronomie lyonnaise": "Lyon cuisine",
  "Gastronomie périgourdine": "Périgord cuisine",
  "Gastronomie Pic": "Maison Pic cuisine",
  "Gastronomie": "gastronomy",
  "Houblon": "hops",
  "Huile d'olive": "olive oil",
  "Huîtres": "oysters",
  "Jambon de Bayonne": "Bayonne ham",
  "Melon de Cavaillon": "Cavaillon melons",
  "Mouchoir de Cholet": "Cholet handkerchief",
  "Noix du Périgord": "Périgord walnuts",
  "Nougat de Montélimar": "Montélimar nougat",
  "Oignons de Roscoff AOP": "Roscoff onions (AOP)",
  "Pastilles Vichy": "Vichy pastilles",
  "Poulet de Bresse": "Bresse chicken",
  "Pruneau d'Agen": "Agen prunes",
  "Pruneaux d'Agen": "Agen prunes",
  "Rillettes vs rillons": "rillettes and rillons",
  "Savon": "soap",
  "Tomate de Marmande": "Marmande tomatoes",
  "Truffes": "truffles",
  "Truffe": "truffles",
  "Vignoble alsacien": "Alsace vineyards",
  "Vignoble bordelais": "Bordeaux vineyards",
  "Vignoble champenois": "Champagne vineyards",
  "Vignoble de Cahors": "Cahors vineyards",
  "Vignoble de Champagne": "Champagne vineyards",
  "Vignoble de Chinon": "Chinon vineyards",
  "Vignoble jurassien": "Jura vineyards",
  "Vignoble Muscadet": "Muscadet vineyards",
  "Vignoble nantais": "Nantes vineyards",
  "Vignoble": "vineyards",
  "Vignobles AOC Bandol": "Bandol AOC vineyards",
  "Vignobles bordelais": "Bordeaux vineyards",
  "Vignobles Corbières": "Corbières vineyards",
  "Vignobles Côte-Rôtie": "Côte-Rôtie vineyards",
  "Vignobles Côtes du Rhône": "Côtes du Rhône vineyards",
  "Vignobles de Bourgogne": "Burgundy vineyards",
  "Vignobles de Saint-Émilion": "Saint-Émilion vineyards",
  "Vignobles de Touraine": "Touraine vineyards",
  "Vignobles des Côtes du Rhône": "Côtes du Rhône vineyards",
  "Vignobles du Languedoc": "Languedoc vineyards",
  "Vignobles du Madiran": "Madiran vineyards",
  "Vignobles Hermitage": "Hermitage vineyards",
  "Vignobles UNESCO": "UNESCO vineyards",
  "Vignobles": "vineyards",
  "Vin blanc de Cassis": "Cassis white wine",
  "Vin de Bandol": "Bandol wine",
  "Vin de Cahors Malbec": "Cahors Malbec wine",
  "Vins AOC Gaillac": "Gaillac AOC wines",
  "Fête des vins": "wine festival",
  "Caves": "wine cellars",
  "Distilleries": "distilleries",
  "Lavande": "lavender",
  "Ocre": "ochre",
  "Oliveraies": "olive groves",
  "Palmiers": "palm trees",
  "Pinède landaise": "Landes pine forest",
  "Pinède": "pine forest",
  "Flamants roses": "flamingos",
  "Chevaux blancs": "white horses",
  "Taureaux": "bulls",

  // Culture, histoire, activités
  "Albert Dubout": "Albert Dubout",
  "Alpinisme": "mountaineering",
  "Antiquaires": "antique dealers",
  "Antiquités": "antiques",
  "Architecture italianisante": "Italianate architecture",
  "Art naïf": "naïve art",
  "Art roman": "Romanesque art",
  "Artisanat": "crafts",
  "Artisans d'art": "craft workshops",
  "Automates": "automata",
  "Bande dessinée": "comics",
  "Bastide médiévale": "medieval bastide",
  "Bastides du Quercy": "Quercy bastides",
  "Bastides": "bastide towns",
  "Bénédictins": "Benedictines",
  "Berceau du cinéma": "birthplace of cinema",
  "Brocante": "flea markets",
  "Céramique": "ceramics",
  "Cerfs-volants": "kites",
  "Corsaires": "corsairs",
  "Cyclisme": "cycling",
  "Dentelle": "lace",
  "Ducs de Savoie": "Dukes of Savoy",
  "Escalade & randonnée": "climbing and hiking",
  "Famille": "family outings",
  "Fauvisme": "Fauvism",
  "Férias": "ferias",
  "Festival d'Avignon": "Avignon Festival",
  "Festival de Cannes": "Cannes Film Festival",
  "Festival du cinéma": "film festival",
  "Festival du Film Américain": "American Film Festival",
  "Foire de Beaucaire": "Beaucaire fair",
  "Foire de Béré": "Béré fair",
  "François Ier": "Francis I",
  "Guerres de Vendée": "Vendée Wars",
  "Guillaume le Conquérant": "William the Conqueror",
  "Héritage mexicain": "Mexican heritage",
  "Histoire cathare": "Cathar history",
  "Horlogerie": "watchmaking",
  "Hydraviation": "seaplanes",
  "Imagerie d'Épinal": "Épinal prints",
  "Impressionnisme": "Impressionism",
  "Impressionnistes": "Impressionists",
  "Industrie": "industry",
  "Jacques Cœur": "Jacques Cœur",
  "Jazz à Vienne": "Jazz à Vienne festival",
  "Jeanne d'Arc": "Joan of Arc",
  "JO 1968": "1968 Winter Olympics",
  "JO 1992": "1992 Winter Olympics",
  "Joutes nautiques": "water jousting",
  "Léonard de Vinci": "Leonardo da Vinci",
  "Magasins d'usine": "factory outlets",
  "Médiéval": "medieval heritage",
  "Napoléon III": "Napoleon III",
  "Noël": "Christmas",
  "Patrimoine religieux": "religious heritage",
  "Patrimoine UNESCO": "UNESCO heritage",
  "Patrimoine": "heritage",
  "Patrouille de France": "Patrouille de France",
  "Pèlerinage": "pilgrimage",
  "Pétrochimie": "petrochemicals",
  "Plongée": "diving",
  "Préhistoire": "prehistory",
  "Reconstruction": "post-war reconstruction",
  "Saint-Jacques-de-Compostelle": "Camino de Santiago",
  "Compostelle": "Camino de Santiago",
  "Sidérurgie": "steel industry",
  "Ski chic": "upmarket skiing",
  "Ski soleil": "sunny skiing",
  "Ski Pra-Loup / Le Sauze": "Pra-Loup and Le Sauze skiing",
  "Spectacles": "shows",
  "Technologie": "technology",
  "Technopole": "technology park",
  "Textile": "textile heritage",
  "Thermalisme Vichy": "Vichy spa tradition",
  "Thermalisme": "spa tradition",
  "Thermal": "spa town",
  "Université": "university",
  "Hippodrome de Chantilly": "Chantilly racecourse",
  "Hippodrome": "racecourse",
  "Tramway": "tramway",
  "Nuit": "night rides",
  "Vol": "flights",
  "Retour": "return trip",
  "Rapide": "fast",
  "Parfumerie": "perfumery",
  "Parfums": "perfumes",
  "Corrida": "bullfighting",
  "Pelote": "Basque pelota",
  "Pointus": "pointu fishing boats",
  "Sardine": "sardines",
  "Calade": "cobbled lanes",
};

/**
 * Libellés courts ou proches d'un mot anglais (« Direct », « Port »,
 * « Terminal ») : on ne les traduit que lorsqu'ils forment un élément entier
 * de la liste des points forts, jamais au milieu d'une phrase anglaise.
 */
const ITEMS_EN: Record<string, string> = {
  Direct: "direct ride",
  Port: "the harbour",
  Terminal: "the terminal",
  "Terminal 1 & 2": "Terminals 1 and 2",
  "Terminal 2": "Terminal 2",
  Île: "the island",
  Opéra: "the opera house",
  Art: "art",
  Golf: "golf",
  Nature: "nature",
  Design: "design",
  Business: "business travel",
  Festival: "festival",
  Feria: "feria",
  Surf: "surfing",
  Ski: "skiing",
  Shopping: "shopping",
  Casino: "casino",
  Panorama: "panoramic views",
  "Panorama océan": "ocean views",
  Architecture: "architecture",
  Renaissance: "Renaissance heritage",
  Rugby: "rugby",
  Rafting: "rafting",
  Thalasso: "thalassotherapy",
  International: "international",
  Dune: "sand dune",
  Baie: "the bay",
  Marais: "Marais",
  Polders: "polders",
  Arsenal: "arsenal",
  Vin: "wine",
  Nougat: "nougat",
  Cassoulet: "cassoulet",
  Mirabelle: "mirabelle plums",
  Reblochon: "Reblochon cheese",
  Pintxos: "pintxos",
  Remblai: "seafront promenade",
  Bastide: "bastide",
  "Baie classée UNESCO": "UNESCO-listed bay",
  "Base Nature & vignobles": "Base Nature and vineyards",
  "Altitude 1800m": "1,800 m altitude",
  Altitude: "altitude",
  Atomium: "Atomium",
  BD: "comics",
  Fonseranes: "Fonseranes locks",
  "Grand Prix": "Grand Prix",
  "Outlet shopping": "outlet shopping",
  "Duty-free": "duty-free",
  "Jet-set": "jet set",
  "Mutuelles": "insurers' headquarters",
  "Melun 2": "Melun 2",
  "Romaine": "Roman heritage",
};

/** Itinéraires écrits en français dans le texte anglais. */
const ITINERAIRES: Array<[RegExp, string]> = [
  [/^Route directe route,/, "Direct route,"],
  [/^Basse Corniche route,/, "Via the lower corniche road,"],
  [/\bvia Ponte Leccia et la Balagne\b/g, "via Ponte Leccia and the Balagne"],
  [/\bvia Corte et col de Vizzavona\b/g, "via Corte and the Col de Vizzavona"],
  [/\bvia Propriano et\b/g, "via Propriano and"],
  [/\bvia le défilé de Lancone\b/g, "via the Lancone gorge"],
  [/\bvia col de Braus\b/g, "via the Col de Braus"],
  [/ (?:then|puis) sortie /g, " then exit "],
  [/\(sortie /g, "(exit "],
  [/\bvia Guillaumes et col de la Cayolle\b/g, "via Guillaumes and the Col de la Cayolle"],
  [/,? sortie (\d+) (?=[A-Z])/g, ", exit $1, "],
  [/,? sortie /g, ", exit "],
  [/\bdirection /g, "towards "],
  [/ ou /g, " or "],
  [/ et (?=[A-Z]?\d)/g, " and "],
  [/ \+ viaduc\b/g, " + viaduct"],
  [/\bvia pont Kehl\b/g, "via the Kehl bridge"],
  [/ par (?=[A-Z])/g, " via "],
  [/ puis /g, " then "],
  [/,,/g, ","],
];

const LIMITE = "(?<![\\p{L}\\p{N}'’-])";
const FIN = "(?![\\p{L}\\p{N}'’-])";

function echapper(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Mots seuls traduits partout : exonymes sans ambiguïté. Les autres mots
 * seuls (« Château », « Forêt », « Plage »…) ouvrent souvent un nom propre
 * absent du dictionnaire (« Château de Chambord ») ; on ne les traduit que
 * comme élément entier d'une liste, avec ITEMS_EN.
 */
const MOTS_SURS = new Set([
  "Allemagne", "Anvers", "Bade", "Bade-Wurtemberg", "Belgique", "Bourgogne", "Bretagne",
  "Bruxelles", "Catalogne", "Corse", "Courtrai", "Espagne", "Flandre", "Forêt-Noire",
  "Gascogne", "Gênes", "Italie", "Ligurie", "Normandie", "Pays-Bas", "Picardie", "Piémont",
  "Pyrénées", "Rhin", "Sarre", "Savoie", "Suisse", "Wallonie", "Alpes", "Méditerranée",
  "Navette", "Périphérique", "Rocade", "Francilienne", "Porte-à-porte",
  "Frontaliers", "Transfrontalier", "Transmanche", "périphérique", "gratuite",
]);
for (const k of Object.keys(PHRASES_EN)) {
  if (!/\s/.test(k) && !MOTS_SURS.has(k)) {
    if (!(k in ITEMS_EN)) ITEMS_EN[k] = PHRASES_EN[k];
    delete PHRASES_EN[k];
  }
}

// Les entrées identiques restent dans le motif d'anglaiser() : elles protègent
// un nom propre (« Suisse Normande ») de la traduction d'un mot qu'il contient.

const ITEMS_TRIES = Object.keys(ITEMS_EN).sort((a, b) => b.length - a.length);
// Un élément de liste : précédé d'un début de phrase ou d'une virgule, suivi
// d'une virgule, de « and », d'un point ou de « along the way / en route ».
const MOTIF_ITEMS = new RegExp(
  `(^|\\. |, |and )(${ITEMS_TRIES.map(echapper).join("|")})(?=,| and | en route| along the way|\\.|$)`,
  "gu",
);

function majusculeDebut(s: string): string {
  return s.replace(new RegExp("(^|[.!?]\\s+)(\\p{Ll})", "gu"), (_, a: string, b: string) => a + b.toUpperCase());
}

/** Traduit les passages français connus d'un texte anglais. */
export function anglaiser(texte: string, noms: Record<string, string> = {}): string {
  // Les noms de départ et d'arrivée entrent dans le même motif que les
  // libellés : le plus long l'emporte, si bien que « Cathédrale de Rouen » est
  // traduit en entier, tandis que « Alpes » n'est pas touché dans le nom
  // « Aéroport Lyon Saint-Exupéry » (rendu « Lyon Saint-Exupéry Airport »).
  const table: Record<string, string> = { ...PHRASES_EN };
  for (const [nom, en] of Object.entries(noms)) {
    const n = nom.normalize("NFC");
    if (n && !(n in PHRASES_EN)) table[n] = en.normalize("NFC");
  }
  const cles = Object.keys(table).sort((a, b) => b.length - a.length);
  const motif = new RegExp(`${LIMITE}(?:${cles.map(echapper).join("|")})${FIN}`, "gu");
  // Certaines saisies sont en Unicode décomposé (« e » + accent combinant) :
  // on recompose pour que « Aéroport Beauvais-Tillé » soit reconnu.
  let s = texte.normalize("NFC");
  for (const [m, remplacement] of ITINERAIRES) s = s.replace(m, remplacement);
  s = s.replace(motif, (m) => table[m]);
  s = s.replace(MOTIF_ITEMS, (_, avant: string, m: string) => avant + ITEMS_EN[m]);
  return majusculeDebut(s);
}

/** Un point fort, traduit pour la liste visible de la page anglaise. */
export function pointFortEn(point: string): string {
  const h = point.normalize("NFC");
  const t = ITEMS_EN[h] ?? PHRASES_EN[h] ?? anglaiser(h);
  return t.charAt(0).toUpperCase() + t.slice(1);
}

/** Itinéraire habituel (champ autoroute, saisi en français). */
export function autorouteEn(autoroute: string): string {
  const s = anglaiser(autoroute);
  // Au milieu de « The usual route takes … », un nom commun reste en minuscule.
  return /^(Southern|Western|Eastern|Lower|Middle|Ring|Direct|Paris ring)\b/.test(s)
    ? "the " + s.charAt(0).toLowerCase() + s.slice(1)
    : s;
}

/** Précisions entre parenthèses ou en fin de champ péages. */
const PEAGES_SUITE: Array<[RegExp, string]> = [
  [/ \(inclus(?: dans le prix)?\)/g, ""],
  [/ \((A\d+ \+ A\d+) péages inclus dans le prix\)/g, " ($1)"],
  [/ de péages?/g, ""],
  [/ \(section Nice–frontière \+ péage italien\)/g, " (Nice to the border, plus the Italian toll)"],
  [/ \(section ([^)]+?) via (A\d+)\)/g, " ($1 section, via the $2)"],
  [/ \(section ([^)]+?) (A\d+)\)/g, " ($1 section, $2)"],
  [/ \(sections ([^)]+)\)/g, " ($1 sections)"],
  [/ \(section ([^)]+)\)/g, " ($1 section)"],
  [/\(péages? (A\d+(?: \+ AP-\d+)?)\)/g, "($1)"],
  [/\bpéages français \+ italiens combinés\b/g, "French and Italian tolls combined"],
  [/\bpéages français \+ italiens\b/g, "French and Italian tolls"],
  [/\+ péage italien\b/g, "+ Italian toll"],
  [/\bpéage A22 français, autoroute belge gratuite\b/g, "French A22 toll, Belgian motorway free"],
  [/\bpéages? (A\d+(?: \+ AP-\d+)?)\b/g, "$1 tolls"],
  [/\bA65, autoroute la plus chère de France au km\b/g, "A65, France's most expensive motorway per km"],
  [/\bA13 \+ Pont de Tancarville ou Normandie\b/g, "A13 + Tancarville or Normandy bridge"],
  [/\(dont Pont de Normandie\)/g, "(including the Pont de Normandie)"],
  [/\((?:France|côté français) uniquement\)/g, "(French side only)"],
  [/\((A\d+) uniquement\)/g, "($1 only)"],
  [/\bA68 courte section\b/g, "short A68 section"],
  [/ tunnel/g, " for the tunnel"],
  [/\(viaduc de Millau\)/g, "(Millau Viaduct)"],
  [/\(viaduc\)/g, "(viaduct)"],
  [/\(pont\)/g, "(bridge)"],
  [/ par A8 \(ou aucun par la côte\)/g, " via the A8 (none along the coast)"],
  [/ (?:par|via) (A\d+)/g, " via the $1"],
  [/\baéroport\b/g, "airport"],
  [/\bfrontière\b/g, "border"],
];

const SANS_PEAGE: Array<[RegExp, string]> = [
  [/^ sur ce trajet$/, ""],
  [/^ \(pas de péage\)$/, ""],
  [/^ \(pas d'autoroute\)$/, " (no motorway)"],
  [/^ \(voies? express bretonnes?\)$/, " (Breton expressway)"],
  [/^ \(route nationale\)$/, " (main road)"],
  [/^ \(route nationale (N\d+)\)$/, " ($1 main road)"],
  [/^ \(routes? départementales?(?: uniquement)?\)$/, " (local roads)"],
  [/^ \(route départementale (D\d+)\)$/, " ($1 local road)"],
  [/^ côté français$/, " on the French side"],
  [/^ \(via (N\d+)\)$/, " (via the $1)"],
  [/^ par (D\d+)$/, " via the $1"],
  [/^ \((A\d+|D\d+)\)$/, " ($1)"],
  [/^ \((A\d+) gratuite\)$/, " (toll-free $1)"],
  [/^ \(itinéraire par la Basse Corniche\)$/, " (via the lower corniche road)"],
  [/^ \(autoroute des Estuaires (A\d+)\)$/, " ($1 Estuaries motorway)"],
  [/^ \(voie express (N\d+) gratuite\)$/, " (toll-free $1 expressway)"],
  [/^ \((A\d+) sans péage sur ce tronçon\)$/, " (toll-free $1 section)"],
  [/^ \(itinéraire sans péage possible via ([^)]+)\)$/, " (toll-free route possible via $1)"],
];

/**
 * Champ péages (saisi en français : « ~4 € (inclus) », « Gratuit (voie
 * express bretonne) ») rendu pour « The usual route takes …, with ___ ».
 */
export function peagesEn(peages: string): string {
  const p = peages.normalize("NFC").trim();
  const prix = (n: string) => `~€${n.replace(",", ".")}`;
  let m = p.match(/^gratuit \((D\d+)\) ou ~(\d+(?:,\d+)?) € \((A\d+)\)$/i);
  if (m) return `no tolls via the ${m[1]}, or ${prix(m[2])} in tolls via the ${m[3]}`;
  m = p.match(/^Péage (A\d+) environ (\d+(?:,\d+)?) €$/);
  if (m) return `${prix(m[2])} in tolls (${m[1]})`;
  m = p.match(/^Environ (\d+(?:,\d+)?) € de péage sur l'(A\d+)$/);
  if (m) return `${prix(m[1])} in tolls on the ${m[2]}`;
  m = p.match(/^(?:gratuite?|aucun(?: péage)?|0 €)(.*)$/i);
  if (m) {
    let suite = m[1];
    for (const [r, en] of SANS_PEAGE) if (r.test(suite)) { suite = suite.replace(r, en); break; }
    return `no tolls${suite}`;
  }
  m = p.match(/^~(\d+(?:,\d+)?) €(.*)$/);
  if (m) {
    let suite = m[2];
    for (const [r, en] of PEAGES_SUITE) suite = suite.replace(r, en);
    return `${prix(m[1])} in tolls${suite}`;
  }
  return anglaiser(p);
}

/** Fourchette de prix saisie en français (« 50 — 62 € »). */
export function prixEstimeEn(prix: string): string {
  const m = prix.normalize("NFC").match(/^(\d+)\s*[—–-]\s*(\d+)\s*€$/);
  if (m) return `€${m[1]} to €${m[2]}`;
  const u = prix.match(/^(\d+)\s*€$/);
  return u ? `€${u[1]}` : prix;
}
